name: Node testing

on:
  push:
    
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Install Node.js
      - uses: actions/setup-node@v4
        continue-on-error: true
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Installing dependances
        run: npm install
      - run: npm run build --if-present
      - run: npm test

