name: Testing Python


on:
  push:

jobs:
  build-python:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
        name:  Install Python
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Run Python script
        run: python3 main.py