name: Testing Python


on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    # environment: production
    steps:
      - uses: actions/checkout@v4
        continue-on-error: true
        name:  Install Python
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: 'pip'
          architecture: 'x64'
      - name: Run Python script
        run: python3 main.py
      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'pip'
      - name: Install pytest
        run: |
          python -m pip install pytest pytest-cov
          pytest test.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
            name: Upload pytest tests results
            path: tests-results.txt
            if-no-files-found: error
        if: ${{ always() }}