name: GitHub Actions demo

run-name: ${{ github.actor }}

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest 
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}"
      - run: echo "The job is running on ${{ runner.os }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} respository has been cloned to the runner."
      - run: echo "The workflow is now ready"
      - name: List files in the repository 
        run: |
          ls ${{ github.workflow }}
      - run: echo "Thi job's status is ${{ job.status }}"

